FROM node:16-alpine as setup

# INSTALL
WORKDIR /shared
COPY /shared/package*.json ./
RUN npm install

WORKDIR /frontend
COPY /frontend/package*.json ./
RUN npm install

# BUILD
WORKDIR /shared
COPY /shared ./

WORKDIR /frontend
COPY /frontend ./

# HOST
CMD ["npm", "run", "buildDev"]