FROM node:16-alpine as setup

# INSTALL
WORKDIR /shared
COPY /shared/package*.json ./
RUN npm install

WORKDIR /frontend
COPY /frontend/package*.json ./
RUN npm install

# BUILD
WORKDIR /shared
COPY /shared ./

WORKDIR /frontend
COPY /frontend ./

# HOST
ENV CHOKIDAR_USEPOLLING=TRUE
# ^ env fixes dockerized file-watching on windows, should be safe to remove on linux for reduced CPU usage. info: https://vitejs.dev/config/server-options.html#server-watch, https://github.com/microsoft/WSL/issues/4739 (didn't declare as vite.config.ts property as this apparently no longer functions)
CMD ["npm", "run", "buildDev"]