version: "3"
services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/nginx/prod.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - proxyToServer
    restart: unless-stopped

  backend:
    volumes:
      - ./backend/admin/admins.json:dist/backend/admin/admins.json
    env_file:
      - ./prod.env
