version: "3"
services:
  nginx_cert:
    image: nginx:1.21.1-alpine
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/devAndCert.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx_cert
    command: sh -c "certbot certonly --webroot -w /tmp/acme_challenge -d distillogue.com --text --agree-tos --email evavkein@gmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme_challenge:/tmp/acme_challenge
    environment:
      - TERM=xterm
