version: "3"
services:
  backend:
    image: distillogue-backend_dev
    container_name: backend_dev
    build:
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./backend/src:/backend/src

  frontend:
    image: distillogue-frontend_dev
    container_name: frontend_dev
    build:
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./frontend/src:/frontend/src
    restart: unless-stopped
