version: "3"
services:
  backend:
    build:
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./backend/src:/backend/src

  frontend:
    build:
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./frontend/src:/frontend/src
    restart: unless-stopped
