version: "3"
services:

  mongodb:
    image: "mongo"
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

  backend:
    build:
      context: ./
      dockerfile: ./backend/dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
    volumes:
      - webfiles:/frontend

  frontend:
    build: 
      context: ./
      dockerfile: ./frontend/dockerfile
    volumes:
      - webfiles:/frontend

volumes:
  webfiles: