version: "3"
services:

  nginx:
    build:
      dockerfile: ./backend/nginx/prod.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.prod.conf:/etc/nginx/nginx.conf