version: "3"
services:
  mongodb:
    image: mongo
    command:
      - --logpath
      - /var/log/mongodb/mongod.log
    networks:
      - serverToDb
    restart: unless-stopped

  backend_dev:
    depends_on:
      - mongodb
      - frontend_dev
    build:
      context: ./
      dockerfile: ./backend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - ./backend/src:/backend/src
      - webfiles:/frontend
    networks:
      - serverToDb
    ports:
      - 3000:3000
    restart: unless-stopped

  frontend_dev:
    build:
      context: ./
      dockerfile: ./frontend/dockerfile.dev
    volumes:
      - ./shared:/shared
      - webfiles:/frontend
      - ./frontend/src:/frontend/src
    restart: unless-stopped

volumes:
  webfiles:

networks:
  serverToDb:
    name: custom_serverToDb
