version: "3"
services:

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxyToServer
    restart: unless-stopped

  mongodb:
    image: "mongo"
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
    networks:
      - serverToDb
    restart: unless-stopped

  backend:
    depends_on:
      - mongodb
      - frontend
    build:
      context: ./
      dockerfile: ./backend/dockerfile
    volumes:
      - webfiles:/frontend
    networks:
      - proxyToServer
      - serverToDb
    restart: unless-stopped

  frontend:
    build: 
      context: ./
      dockerfile: ./frontend/dockerfile
    volumes:
      - webfiles:/frontend

volumes:
  webfiles:

networks:
  proxyToServer:
    name: custom_proxyToServer
  serverToDb:
    name: custom_serverToDb