version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./backend/nginx/prod.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/nginx/prod.nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - proxyToServer
    restart: unless-stopped
