version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./backend/nginx/prod.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/nginx/prod.nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxyToServer
    restart: unless-stopped
