FROM node:16-alpine as setup

# INSTALL
WORKDIR /shared
COPY /shared/package*.json /shared/
RUN npm install

WORKDIR /backend
COPY /backend/package*.json /backend/
RUN npm install

# BUILD
WORKDIR /shared
COPY /shared /shared/

WORKDIR /backend
COPY /backend /backend/
RUN npm run build

# CLEAN
FROM node:16-alpine
WORKDIR /backend
COPY --from=setup /backend/package.json ./
RUN npm install --omit=dev
COPY --from=setup /backend/dist ./dist/

# HOST
EXPOSE 3000
ENV DOCKERIZED=TRUE
CMD ["npm", "run", "server"]