name: E2E Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  Playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Launch project
        run: docker-compose up --detach

      - name: Launch tests
        run: CI=TRUE docker-compose -f docker-compose.tests.yaml up

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./testing/playwright-report/
          retention-days: 7
