name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Launch containers
        run: docker-compose up --detach

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: testing/cypress/e2e
          browser: chrome
